language: python
python:
  - 3.9

install: 
  - pip install -r requirements.txt

script: 
  - python3 test/Framework.py "-e" "ALL" "-f" "./data/auto93.csv" "-n" "512"

notifications:
  email:
    recipients: 
      - vchalla2@ncsu.edu
      - sbangal3@ncsu.edu
      - kprawat@ncsu.edu
      - sponnur@ncsu.edu
      - svsakham@ncsu.edu
    
    on_success: never
    on_failure: always