language: python
python:
  - 3.6

install: 
  - pip install -r requirements.txt

script: 
  - python3 test/Framework.py

notifications:
  email:
    recipients: 
      - vchalla2@ncsu.edu
      - sbangal3@ncsu.edu
      - kprawat@ncsu.edu
      - sponnur@ncsu.edu
      - svsakham@ncsu.edu
    
    on_success: never
    on_failure: always